// This file was generated by silverstripe/cow from client/lang/src/bg.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('bg', {
    "CampaignAdmin.ADDCAMPAIGN": "Добави кампания",
    "CampaignAdmin.DELETECAMPAIGN": "Да бъде ли изтрит този запис?",
    "CampaignAdmin.DRAFT": "Чернова",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s елемента",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s елемент",
    "CampaignAdmin.MODIFIED": "Променена",
    "CampaignAdmin.NO_CHANGES": "Без промени",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Публикувай кампания",
    "CampaignAdmin.REMOVED": "Премахната",
    "CampaignAdmin.REVERTCAMPAIGN": "Възстановена"
});
}