// This file was generated by silverstripe/cow from client/lang/src/cs.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('cs', {
    "CampaignAdmin.DRAFT": "Draft",
    "CampaignAdmin.MODIFIED": "Modified",
    "CampaignAdmin.REMOVED": "Removed",
    "CampaignAdmin.NO_CHANGES": "No changes",
    "CampaignAdmin.ADDCAMPAIGN": "Přidat kampaň",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s položek",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s položka",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Zveřejnit kampaň",
    "CampaignAdmin.REVERTCAMPAIGN": "Přepnout"
});
}