// This file was generated by silverstripe/cow from admin/client/lang/src/en.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "CampaignAdmin.ADDCAMPAIGN": "Add campaign",
    "CampaignAdmin.DELETECAMPAIGN": "Are you sure you want to delete this record?",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s items",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s item",
    "CampaignAdmin.LOADING": "Loading...",
    "CampaignAdmin.NO_RECORDS": "No campaigns created yet.",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Publish campaign",
    "CampaignAdmin.REVERTCAMPAIGN": "Revert",
    "CampaignAdmin.DRAFT": "Draft",
    "CampaignAdmin.MODIFIED": "Modified",
    "CampaignAdmin.REMOVED": "Removed",
    "CampaignAdmin.NO_CHANGES": "No changes"
});
}
