// This file was generated by silverstripe/cow from admin/client/lang/src/en.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "Campaigns.ADDCAMPAIGN": "Add campaign",
    "Campaigns.DELETECAMPAIGN": "Are you sure you want to delete this record?",
    "Campaigns.ITEM_SUMMARY_PLURAL": "%s items",
    "Campaigns.ITEM_SUMMARY_SINGULAR": "%s item",
    "Campaigns.LOADING": "Loading...",
    "Campaigns.NO_RECORDS": "No campaigns created yet.",
    "Campaigns.PUBLISHCAMPAIGN": "Publish campaign",
    "Campaigns.REVERTCAMPAIGN": "Revert"
});
}
