// This file was generated by silverstripe/cow from client/lang/src/eo.js.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "CampaignAdmin.DRAFT": "Draft",
    "CampaignAdmin.MODIFIED": "Modified",
    "CampaignAdmin.REMOVED": "Removed",
    "CampaignAdmin.NO_CHANGES": "No changes",
    "CampaignAdmin.ADDCAMPAIGN": "Aldoni kampanjon",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s elementoj",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s elemento",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Publikigi kampanjon",
    "CampaignAdmin.REVERTCAMPAIGN": "Malfari"
});
}