// This file was generated by silverstripe/tx-translator from client/lang/src/eo.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "CampaignAdmin.ADDCAMPAIGN": "Aldoni kampanjon",
    "CampaignAdmin.DELETECAMPAIGN": "Ĉu vi vere volas forigi ĉi tiun rikordon?",
    "CampaignAdmin.FORBIDDEN": "Vi ne havas permeson vidi ĉi tiun kampanjon",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s elementoj",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s elemento",
    "CampaignAdmin.PAGE_NOT_FOUND": "Ne povas trovi la kampanjon kiun vi serĉas.",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Publikigi kampanjon",
    "CampaignAdmin.REVERTCAMPAIGN": "Malfari",
    "CampaignAdmin.SOMETHING_WENT_WRONG": "Io malfunkciis."
});
}