// This file was generated by silverstripe/tx-translator from client/lang/src/fa_IR.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fa_IR', {
    "CampaignAdmin.ADDCAMPAIGN": "افزودن کمپین",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s آیتم",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s آیتم",
    "CampaignAdmin.PUBLISHCAMPAIGN": "انتشار کمپین",
    "CampaignAdmin.REVERTCAMPAIGN": "بازگرداندن"
});
}