// This file was generated by silverstripe/cow from client/lang/src/fi.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fi', {
    "CampaignAdmin.ADDCAMPAIGN": "Lisää kampanja",
    "CampaignAdmin.DELETECAMPAIGN": "Haluatko varmasti poistaa tämän tietueen?",
    "CampaignAdmin.DRAFT": "Draft",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s kohdetta",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s kohde",
    "CampaignAdmin.MODIFIED": "Modified",
    "CampaignAdmin.NO_CHANGES": "No changes",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Julkaise kampanja",
    "CampaignAdmin.REMOVED": "Removed",
    "CampaignAdmin.REVERTCAMPAIGN": "Palauta",
    "CampaignAdmin.FORBIDDEN": "You do not have access to view this campaign.",
    "CampaignAdmin.PAGE_NOT_FOUND": "The campaign you are looking for can not be found.",
    "CampaignAdmin.SOMETHING_WENT_WRONG": "Something went wrong."
});
}