// This file was generated by silverstripe/tx-translator from client/lang/src/fi_FI.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fi_FI', {
    "CampaignAdmin.ADDCAMPAIGN": "Lisää kampanja",
    "CampaignAdmin.DELETECAMPAIGN": "Haluatko varmasti poistaa tämän tietueen?",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s kohdetta",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s kohde",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Julkaise kampanja",
    "CampaignAdmin.REVERTCAMPAIGN": "Palauta"
});
}