// This file was generated by silverstripe/cow from client/lang/src/fr.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fr', {
    "CampaignAdmin.ADDCAMPAIGN": "Ajouter une campagne",
    "CampaignAdmin.DELETECAMPAIGN": "Êtes-vous sûr de vouloir supprimer cet enregistrement ?",
    "CampaignAdmin.DRAFT": "Brouillon",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s éléments",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s élément",
    "CampaignAdmin.MODIFIED": "Modifié",
    "CampaignAdmin.NO_CHANGES": "Aucun changement",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Publier la campagne",
    "CampaignAdmin.REMOVED": "Retiré",
    "CampaignAdmin.REVERTCAMPAIGN": "Revenir",
    "CampaignAdmin.FORBIDDEN": "You do not have access to view this campaign.",
    "CampaignAdmin.PAGE_NOT_FOUND": "The campaign you are looking for can not be found.",
    "CampaignAdmin.SOMETHING_WENT_WRONG": "Something went wrong."
});
}