// This file was generated by silverstripe/tx-translator from client/lang/src/hr.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('hr', {
    "CampaignAdmin.ADDCAMPAIGN": "Dodaj kampanju",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s stavki",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s stavka",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Objavi kampanju",
    "CampaignAdmin.REVERTCAMPAIGN": "Vrati"
});
}