// This file was generated by silverstripe/tx-translator from client/lang/src/it.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('it', {
    "CampaignAdmin.ADDCAMPAIGN": "Aggiungi campagna",
    "CampaignAdmin.DELETECAMPAIGN": "Sei sicuro di voler eliminare questo record?",
    "CampaignAdmin.DRAFT": "Bozza",
    "CampaignAdmin.FORBIDDEN": "Non hai accesso ai dati di questa campagna.",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s elementi",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s elemento",
    "CampaignAdmin.MODIFIED": "Modificato",
    "CampaignAdmin.NO_CHANGES": "Nessuna modifica",
    "CampaignAdmin.PAGE_NOT_FOUND": "La campagna che stai cercando non è stata trovata.",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Pubblica campagna",
    "CampaignAdmin.REMOVED": "Eliminato",
    "CampaignAdmin.REVERTCAMPAIGN": "Ripristina",
    "CampaignAdmin.SOMETHING_WENT_WRONG": "Qualcosa è andato storto."
});
}