// This file was generated by silverstripe/cow from client/lang/src/lt.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('lt', {
    "CampaignAdmin.ADDCAMPAIGN": "Add campaign",
    "CampaignAdmin.DELETECAMPAIGN": "Are you sure you want to delete this record?",
    "CampaignAdmin.DRAFT": "Draft",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s items",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s item",
    "CampaignAdmin.MODIFIED": "Modified",
    "CampaignAdmin.NO_CHANGES": "No changes",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Publish campaign",
    "CampaignAdmin.REMOVED": "Removed",
    "CampaignAdmin.REVERTCAMPAIGN": "Revert",
    "CampaignAdmin.FORBIDDEN": "You do not have access to view this campaign.",
    "CampaignAdmin.PAGE_NOT_FOUND": "The campaign you are looking for can not be found.",
    "CampaignAdmin.SOMETHING_WENT_WRONG": "Something went wrong."
});
}