// This file was generated by silverstripe/cow from client/lang/src/nl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "CampaignAdmin.ADDCAMPAIGN": "Campagne toevoegen",
    "CampaignAdmin.DELETECAMPAIGN": "Weet u zeker dat u dit record wilt verwijderen?",
    "CampaignAdmin.DRAFT": "Concept",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s items",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s item",
    "CampaignAdmin.MODIFIED": "Gewijzigd",
    "CampaignAdmin.NO_CHANGES": "Geen wijzigingen",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Campagne publiceren",
    "CampaignAdmin.REMOVED": "Verwijderd",
    "CampaignAdmin.REVERTCAMPAIGN": "Terugdraaien"
});
}