// This file was generated by silverstripe/tx-translator from client/lang/src/nl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "CampaignAdmin.ADDCAMPAIGN": "Campagne toevoegen",
    "CampaignAdmin.DELETECAMPAIGN": "Weet u zeker dat u dit record wilt verwijderen?",
    "CampaignAdmin.DRAFT": "Concept",
    "CampaignAdmin.FORBIDDEN": "Je hebt geen toegang tot deze campagne.",
    "CampaignAdmin.MODIFIED": "Gewijzigd",
    "CampaignAdmin.NO_CHANGES": "Geen wijzigingen",
    "CampaignAdmin.PAGE_NOT_FOUND": "De gezochte campagne kan niet gevonden worden.",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Campagne publiceren",
    "CampaignAdmin.REMOVED": "Verwijderd",
    "CampaignAdmin.REVERTCAMPAIGN": "Terugdraaien",
    "CampaignAdmin.SOMETHING_WENT_WRONG": "Er is iets misgegaan."
});
}