// This file was generated by silverstripe/tx-translator from client/lang/src/pl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('pl', {
    "CampaignAdmin.ADDCAMPAIGN": "Dodaj kampanię",
    "CampaignAdmin.DELETECAMPAIGN": "Czy napewno chcesz usunąć ten rekord?",
    "CampaignAdmin.DRAFT": "Szkic",
    "CampaignAdmin.FORBIDDEN": "Nie masz uprawnień do zobaczenia kampanii",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s rzeczy",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s rzecz",
    "CampaignAdmin.MODIFIED": "Zmodyfikowano",
    "CampaignAdmin.NO_CHANGES": "Brak zmian",
    "CampaignAdmin.PAGE_NOT_FOUND": "Kampania której szukasz nie może zostać odnaleziona.",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Publikuj kampanię",
    "CampaignAdmin.REMOVED": "Usunięto",
    "CampaignAdmin.REVERTCAMPAIGN": "Przywrócono",
    "CampaignAdmin.SOMETHING_WENT_WRONG": "Coś poszło nie tak."
});
}