// This file was generated by silverstripe/tx-translator from client/lang/src/ru.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('ru', {
    "CampaignAdmin.ADDCAMPAIGN": "Добавить кампанию",
    "CampaignAdmin.DELETECAMPAIGN": "Вы действительно хотите удалить эту запись?",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s элементов",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s элемент",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Опубликовать кампанию",
    "CampaignAdmin.REVERTCAMPAIGN": "Отменить"
});
}