// This file was generated by silverstripe/cow from client/lang/src/sk.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "CampaignAdmin.ADDCAMPAIGN": "Pridať kampaň",
    "CampaignAdmin.DELETECAMPAIGN": "Are you sure you want to delete this record?",
    "CampaignAdmin.DRAFT": "Draft",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s položiek",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s položka",
    "CampaignAdmin.MODIFIED": "Modified",
    "CampaignAdmin.NO_CHANGES": "No changes",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Zverejniť kampaň",
    "CampaignAdmin.REMOVED": "Removed",
    "CampaignAdmin.REVERTCAMPAIGN": "Prepnúť"
});
}