// This file was generated by silverstripe/tx-translator from client/lang/src/sk.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "CampaignAdmin.ADDCAMPAIGN": "Pridať kampaň",
    "CampaignAdmin.DELETECAMPAIGN": "Naozaj chcete odstrániť tento záznam?",
    "CampaignAdmin.DRAFT": "Koncept",
    "CampaignAdmin.FORBIDDEN": "Nemáte prístup na zobrazenie tejto kampane.",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s položiek",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s položka",
    "CampaignAdmin.MODIFIED": "Upravené",
    "CampaignAdmin.NO_CHANGES": "Žiadne zmeny",
    "CampaignAdmin.PAGE_NOT_FOUND": "Kampaň, ktorú hľadáte, nie je možné nájsť.",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Zverejniť kampaň",
    "CampaignAdmin.REMOVED": "Odstránené",
    "CampaignAdmin.REVERTCAMPAIGN": "Vrátiť späť",
    "CampaignAdmin.SOMETHING_WENT_WRONG": "Niečo sa pokazilo."
});
}