// This file was generated by silverstripe/cow from client/lang/src/sl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl', {
    "CampaignAdmin.ADDCAMPAIGN": "Dodaj kampanjo",
    "CampaignAdmin.DELETECAMPAIGN": "Res želite izbrisati ta zapis?",
    "CampaignAdmin.DRAFT": "Osnutek",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s elementov",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s element",
    "CampaignAdmin.MODIFIED": "Spremenjeno",
    "CampaignAdmin.NO_CHANGES": "Brez sprememb",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Objavi kampanjo",
    "CampaignAdmin.REMOVED": "Odstranjeno",
    "CampaignAdmin.REVERTCAMPAIGN": "Povrni"
});
}