// This file was generated by silverstripe/cow from client/lang/src/sl_SI.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl_SI', {
    "CampaignAdmin.ADDCAMPAIGN": "Dodaj kampanjo",
    "CampaignAdmin.DELETECAMPAIGN": "Are you sure you want to delete this record?",
    "CampaignAdmin.DRAFT": "Draft",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "% predmetov",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s predmet",
    "CampaignAdmin.MODIFIED": "Modified",
    "CampaignAdmin.NO_CHANGES": "No changes",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Objavi kampanjo",
    "CampaignAdmin.REMOVED": "Removed",
    "CampaignAdmin.REVERTCAMPAIGN": "Povrni"
});
}