// This file was generated by silverstripe/cow from client/lang/src/sv.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sv', {
    "CampaignAdmin.ADDCAMPAIGN": "Lägg till kampanj",
    "CampaignAdmin.DELETECAMPAIGN": "Är du säker på att du vill ta bort denna posten?",
    "CampaignAdmin.DRAFT": "Utkast",
    "CampaignAdmin.ITEM_SUMMARY_PLURAL": "%s objekt",
    "CampaignAdmin.ITEM_SUMMARY_SINGULAR": "%s objekt",
    "CampaignAdmin.MODIFIED": "Ändrad",
    "CampaignAdmin.NO_CHANGES": "Inga ändringar",
    "CampaignAdmin.PUBLISHCAMPAIGN": "Publicera kampanj",
    "CampaignAdmin.REMOVED": "Raderad",
    "CampaignAdmin.REVERTCAMPAIGN": "Återgå"
});
}