export default {
  SET_CAMPAIGN_ACTIVE_CHANGESET: 'SET_CAMPAIGN_ACTIVE_CHANGESET',
  SET_CAMPAIGN_SELECTED_CHANGESETITEM: 'SET_CAMPAIGN_SELECTED_CHANGESETITEM',
  PUBLISH_CAMPAIGN_REQUEST: 'PUBLISH_CAMPAIGN_REQUEST',
  PUBLISH_CAMPAIGN_SUCCESS: 'PUBLISH_CAMPAIGN_SUCCESS',
  PUBLISH_CAMPAIGN_FAILURE: 'PUBLISH_CAMPAIGN_FAILURE',
  SET_NEW_CAMPAIGN: 'SET_NEW_CAMPAIGN',
  REMOVE_CAMPAIGN_ITEM_REQUEST: 'REMOVE_CAMPAIGN_ITEM_REQUEST',
  REMOVE_CAMPAIGN_ITEM_SUCCESS: 'REMOVE_CAMPAIGN_ITEM_SUCCESS',
  REMOVE_CAMPAIGN_ITEM_FAILURE: 'REMOVE_CAMPAIGN_ITEM_FAILURE',
  SET_SHOW_MESSAGE: 'SET_SHOW_MESSAGE',
};
