---
Name: campaignadmin
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_i18n:
    - 'silverstripe/campaign-admin: client/lang'
  extra_requirements_javascript:
    - 'silverstripe/campaign-admin: client/dist/js/bundle.js'
  extra_requirements_css:
    - 'silverstripe/campaign-admin: client/dist/styles/bundle.css'

# Allow users only only have access to the campaign-admin, and not all CMS access
# i.e. CMS_ACCESS_LeftAndMain, to still be able to manage changesets
SilverStripe\Versioned\ChangeSet:
  required_permission:
    - CMS_ACCESS_CampaignAdmin
