---
Name: campaignadmin
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_i18n:
    - 'silverstripe/campaign-admin: client/lang'
  extra_requirements_javascript:
    - 'silverstripe/campaign-admin: client/dist/js/bundle.js'
  extra_requirements_css:
    - 'silverstripe/campaign-admin: client/dist/styles/bundle.css'

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\CampaignAdmin\SiteTreeExtension
